services:
  postgres_stag:
    image: postgres:latest
    hostname: ${POSTGRES_HOST}
    container_name: postgres_stag_db
    ports:
      - 5431:5432
    volumes:
      - ./app/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  xera_stag:
    build:
      context: .
      dockerfile: Dockerfile.stag
    ports:
      - 5000:5000
    volumes:
      - ./:/xera_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - postgres_stag
    restart: always
    command: >
      sh -c "
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      npm run stag
      "
