services:
  postgres_local:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5430:5432
    volumes:
      - ./app/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  xera_local:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./:/xera_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres_local
    depends_on:
      - postgres_local
    env_file:
      - .env.local
    # local
    command: >
      sh -c "
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      npm run dev
      "
