services:
  postgres_stag:
    image: postgres:latest
    hostname: ${POSTGRES_HOST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./app-${NODE_ENV}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env.stag
    restart: always

  xera_stag:
    build:
      context: .
      dockerfile: Dockerfile.stag
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/xera_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - ${POSTGRES_HOST}
    env_file:
      - .env.stag
    restart: always
    command: >
      sh -c "
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      npm run stag
      "
