# Fetching the minified node image on apline linux
FROM --platform=linux/amd64 node:slim
# FROM node:slim

# Declaring env
ENV NODE_ENV=local

# Setting up the work directory
WORKDIR /xera_app

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

# Installing Sequelize CLI
RUN npm install -g sequelize-cli

# Exposing server port
EXPOSE 3000

# Starting our application
# CMD [ "node", "app.js" ]

