services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./app/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  xera_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/xera_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    env_file:
      - .env
    # local
    command: >
      sh -c "
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      npm start
      "
