const CaseStatus = {
    NEWCASE: 'NEWCASE',
    INPROGRESS: 'INPROGRESS',
    SENTTOREVIEW: 'SENTTOREVIEW',
    INREVIEW: 'INREVIEW',
    REQUESTCHANGES: 'REQUESTCHANGES',
    FINISHED: 'FINISHED'
};


module.exports = { CaseStatus }
